package com.br.estimativadeprojetodesoftware.view.projeto;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JList;
import javax.swing.JScrollPane;
import javax.swing.JTextField;

/**
 *
 * @author tetzner
 */
public class EdicaoProjetoView extends javax.swing.JDialog {

    /**
     * Creates new form CadastroProjView
     */
    public EdicaoProjetoView() {
        initComponents();
    }

    public JButton getBtnAdicionarPerfil() {
        return btnAdicionarPerfil;
    }

    public JButton getBtnRemoverPerfil() {
        return btnRemoverPerfil;
    }

    public JButton getBtnCadastrarProjeto() {
        return btnCadastrarProjeto;
    }

    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public JComboBox<String> getCbmPerfis() {
        return cbmPerfis;
    }

    public JList<String> getjListPerfis() {
        return jListPerfis;
    }

    public JScrollPane getSpListaPerfis() {
        return spListaPerfis;
    }

    public JTextField getTxtNome() {
        return txtNome;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spListaPerfis = new javax.swing.JScrollPane();
        jListPerfis = new javax.swing.JList<>();
        txtNome = new javax.swing.JTextField();
        btnCadastrarProjeto = new javax.swing.JButton();
        btnAdicionarPerfil = new javax.swing.JButton();
        btnRemoverPerfil = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblCadastroProjeto = new javax.swing.JLabel();
        lblNomeProjeto = new javax.swing.JLabel();
        lblPerfis = new javax.swing.JLabel();
        cbmPerfis = new javax.swing.JComboBox<>();

        setTitle("Cadastro de Projeto");

        spListaPerfis.setViewportView(jListPerfis);

        txtNome.setMaximumSize(new java.awt.Dimension(64, 22));
        txtNome.setName(""); // NOI18N

        btnCadastrarProjeto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCadastrarProjeto.setText("Salvar");

        btnAdicionarPerfil.setText("Adicionar Perfil");

        btnRemoverPerfil.setText("Remover Perfil");

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");

        lblCadastroProjeto.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblCadastroProjeto.setText("Edição de Projeto");

        lblNomeProjeto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNomeProjeto.setText("Nome:");

        lblPerfis.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPerfis.setText("Perfis:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPerfis)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(spListaPerfis, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(cbmPerfis, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAdicionarPerfil)
                            .addComponent(btnRemoverPerfil)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNomeProjeto)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(btnCadastrarProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(123, 123, 123)))
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(lblCadastroProjeto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCadastroProjeto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNomeProjeto)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPerfis)
                            .addComponent(btnAdicionarPerfil)
                            .addComponent(cbmPerfis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(spListaPerfis, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnRemoverPerfil))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrarProjeto)
                    .addComponent(btnCancelar))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarPerfil;
    private javax.swing.JButton btnCadastrarProjeto;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRemoverPerfil;
    private javax.swing.JComboBox<String> cbmPerfis;
    private javax.swing.JList<String> jListPerfis;
    private javax.swing.JLabel lblCadastroProjeto;
    private javax.swing.JLabel lblNomeProjeto;
    private javax.swing.JLabel lblPerfis;
    private javax.swing.JScrollPane spListaPerfis;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
